### ISSUE TITLE
Support v5.8.0

### ISSUE THREAD

**Issue by craftzdog** [skipadu/inkdrop-night-owl-ui#1]
Hi skipadu!

I just released v5.8.0-beta.1, which comes with a bunch of UI improvements:

https://forum.inkdrop.app/t/inkdrop-desktop-v5-8-0-beta-1/4473

It has some accessibility improvements, which require custom themes to update.
The release notes mention how to update your theme.
Could you check it out?

Thanks for creating a great theme!

**Comment by skipadu** [comment]
Thanks for the opened issue craftzdog!
I will try to update the theme to fit the new version (along with the  #2 ).

**Comment by craftzdog** [comment]
You no longer have to work on this issue but only #2.
Thanks for your attention!
Closing.
