### ISSUE TITLE
Support v5.9.0

### ISSUE THREAD

**Issue by craftzdog** [skipadu/inkdrop-night-owl-ui#2]
The new version got a new CSS-variable-based theming system, which makes theming significantly easier:

- Release notes: https://forum.inkdrop.app/t/inkdrop-desktop-v5-9-0-beta-1/5017

While it has some backward compatibility, I'd like this theme to be updated for future updates.

I've updated the theming guide here:

- https://developers.inkdrop.app/guides/create-a-theme

Can you please check it out and update this theme?

**Comment by skipadu** [comment]
Thanks for the information!

I will try to look this at the same time with the #1 when updating the theme.

**Comment by skipadu** [comment]
I created the new version that hopefully is done right and it should have the support for the v5.9.0 of Inkdrop.
_I still need to update syntax and preview theme packages separately._

https://github.com/skipadu/inkdrop-night-owl-ui/releases/tag/v2.0.0

**Comment by craftzdog** [comment]
Thank you, @skipadu 🥳
It seems that the screenshot link is broken in the README. Can you check it?

**Comment by skipadu** [comment]
Was cleaning the old code too much and got rid of the screenshot. Thanks for telling!
Screenshot should now be returned (same old screenshot, I should update it when I have updated all the themes)

**Comment by craftzdog** [comment]
Cool! I confirmed it has been fixed ✅ Thanks again for taking time to update your themes! Cheers
